### ISSUE TITLE
implement Augmentation Service

### ISSUE THREAD

**Issue by ethernian** [dapplets/dapplet-extension#11]
## to be implemented:
- [ ] Feature Augmentation Service (in background.js).
     - [ ] the Service should be two-ways and async.
     - [ ] with binding to the displayed text.
     - [ ] batching should be possible (combine many requests at once)
- [ ] extend dev server by mock service.
- [ ] example in the Feature.
- [ ] sanitize input/output (at least as ToDo)

## Server API proposal (JSON):
```
   server_api = (contextId[]:string, controlClasses: string[]) => {contextId: string, augmText:string[] }[]
   
   request = { 
      contextId:["1133586508982693889","1133586508982693822"], 
      controlClasses: ["dapplet-tweet-south-ethereum-2","dapplet-dm-south-metamask"] 
   }
  
   response = [{      
      contextId:"1133586508982693822", 
      augmText: ["012","deadbeef"] 
   },{      
      contextId:"1133586508982693889", 
      augmText: ["123","abc"] 
   }]
```

https://github.com/dapplets/typescript-examples/blob/9cf90f21d642788b7be7fab84cebe38e950860a2/src/TwitterFeature2/index.ts#L112-L116

![image](https://user-images.githubusercontent.com/4574735/58545857-6ce5f280-8204-11e9-8c15-8f5072034070.png)

**Comment by Lisofffa** [comment]
test

**Comment by Pasternag** [comment]
test 51
