### ISSUE TITLE
implement version support

### ISSUE THREAD

**Issue by ethernian** [dapplets/dapplet-extension#12]
[detailed specification](https://github.com/dapplets/dapplet-main/blob/master/specs/release-1.0/versioning.md)

- [x] `@PublicName` decorator.
- [ ] use [semver module](https://www.npmjs.com/package/semver) in extension's background.js
- [x] An `@Load` decorator.
- [x] An dependency optimizer (empty implementation) 
- [ ] Возможно нужно будет запускать eval в background'e, что опасно. Можно реализовать через песочницу https://developer.chrome.com/extensions/sandboxingEval

**Comment by Pasternag** [comment]
test 21
