### ISSUE TITLE
fix magic lookup of browserify module

### ISSUE THREAD

**Issue by ethernian** [dapplets/dapplet-extension#13]
This dirty hack for browserify module lookup needs to be fixed. 

https://github.com/dapplets/dapplet-extension/blob/fc1fbf930e7416f3d3f2c9f6371472b64e322bac/src/inpage/Injector.ts#L61

from

https://github.com/dapplets/dapplet-extension/blob/fc1fbf930e7416f3d3f2c9f6371472b64e322bac/src/inpage/Injector.ts#L58-L67

**Comment by alsakhaev** [comment]
Closed because target class extractiton principle was changed.

**Comment by Gromazek** [comment]
test 7 14:00

**Comment by Gromazek** [comment]
test 9 14^04

**Comment by Gromazek** [comment]
test 231216_1547

**Comment by Gromazek** [comment]
test 231216_1550

**Comment by Gromazek** [comment]
test 231216_1551

**Comment by Gromazek** [comment]
test 231216_1552
