### ISSUE TITLE
Problems with updating Dapplet Community Invite

### ISSUE THREAD

**Issue by Pasternag** [dapplets/dapplet-extension#28]
1, Update failed or update result is not visible
2. Version of Dapplet not visible (attached picture)
![200930 issue Pict](https://user-images.githubusercontent.com/71752351/94718835-f8244a80-035a-11eb-9a62-6525a0a25440.png)

**Comment by alsakhaev** [comment]
Added the label with the current version of activated dapplet:
![1](https://user-images.githubusercontent.com/15713727/95308376-7f5d4b00-0892-11eb-97c4-6dd245008405.png)

When a version is outdated, the label will be orange:
![2](https://user-images.githubusercontent.com/15713727/95308384-81bfa500-0892-11eb-915b-aa354c250f7a.png)

**Comment by alsakhaev** [comment]
Will be available since v0.17.0

**Comment by Gromazek** [comment]
Test comment for tipping

**Comment by Gromazek** [comment]
test comment
