### ISSUE TITLE
implement a dependency loader

### ISSUE THREAD

**Issue by ethernian** [dapplets/dapplet-extension#3]
Following call is unimplemented yet. Please do.

https://github.com/dapplets/dapplet-extension/blob/0088f7ec4999b6d15bc4bacdfaa05b0c53877459/src/inpage/index.ts#L84-L87

**Comment by ethernian** [comment]
closing for now.
later we should probably use [inversify](http://inversify.io/) or other IoC container.

**Comment by Gromazek** [comment]
test 03
