### ISSUE TITLE
merge isBlockedEverywhere() & isBlockedHostname() into single call.

### ISSUE THREAD

**Issue by ethernian** [dapplets/dapplet-extension#4]
What is the benefit to implement functions isBlockedEverywhere() & isBlockedHostname() as separate calls in inpage? 

It should be the responsibility of the background to report the Blocked status, no matter how it gets calculated, shouldn't it?

https://github.com/dapplets/dapplet-extension/blob/0088f7ec4999b6d15bc4bacdfaa05b0c53877459/src/inpage/index.ts#L91-L102

Proposal (dirty drafted):
```typescript
//===  inpage  ===
if (isBlocked(hostname)) {
...
}
//===  background  ===
isBlocked(hostname:string):boolean {
   return isBlockedEverywhere() || isBlockedHostname(hostname)
}
```

**Comment by Gromazek** [comment]
test 1
