### ISSUE TITLE
simplify devmode configuration

### ISSUE THREAD

**Issue by ethernian** [dapplets/dapplet-extension#8]
The endpoint baseurl setting should be sufficient to access the development server from the extension.

Example:
`http://localhost:8080/twitterdev/` as base url
with directory structure
`./MyTwitterAdapter/**`
`./MyTwitterFeature01/**`
`./MyTwitterFeature02/**`

necessary aliases may be defined in some index file served by http-server from `./`.

**Comment by Pasternag** [comment]
test 31

**Comment by Pasternag** [comment]
test 32
