### ISSUE TITLE
add notifications field to popup

### ISSUE THREAD

**Issue by alsakhaev** [dapplets/dapplet-extension#9]
background generates notices

**Comment by ethernian** [comment]
An implementation proposal
![image](https://user-images.githubusercontent.com/4574735/61619171-9fddbd00-ac6e-11e9-87b7-f655c6f91b93.png)

**Comment by ethernian** [comment]
extract Notifications from Features TAB into separate Events TAB.

**Comment by alsakhaev** [comment]
Need to implement a module updating
